spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/qm_teacher
      username: root
      password: 123456
  application:
    name: teacherService
  main:
    banner-mode: off
  mail:
    host: smtp.qq.com
    username: 2636822826@qq.com
    password: vvtrqzaompnzebjj
  cache:
    type: redis
    redis:
      time-to-live: 300000  #60000
  redis:
    host: localhost
    port: 6379
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8082
mybatis-plus:
#  configuration:
    #日志配置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键生成策略
      id-type: ASSIGN_ID