spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/QM_student
      username: root
      password: 123456
  application:
    name: studentService
  main:
    banner-mode: off
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8083
mybatis-plus:
#  configuration:
#    #日志配置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键生成策略
      id-type: ASSIGN_ID